{
 "title": "Nginx Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Client Connection Accepted/ 1min",
   "type": "timeseries",
   "description": "Total Client Connect Accepted with 1min",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Connect Active/ 1min",
   "type": "timeseries",
   "description": "Total Connection Active with in 1min",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_connections_active[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handled Client Connection/ 1min",
   "type": "timeseries",
   "description": "Total Handled Client Connections in 1min",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(nginx_connections_handled[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "description": "Nginx Status Check",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  }
 ]
}